/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PortalUI;

import AdminUI.AdminLoginJPanel;
import ProfessorUI.ProfessorLoginJPanel;
import ProfessorUI.ProfessorRegisterJPanel;
import StudentUI.StudentLoginJPanel;
import StudentUI.StudentRegisterJPanel;
import ThirdPartyUI.ThirdPartyLoginJPanel;
import business.QueryHistory;
import business.admin;
import business.courseDirectory;
import business.professorDirectory;
import business.studentDirectory;
import business.thirdParty;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author pranavkapse
 */
public class MainPortalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPortalJPanel
     */
    JPanel cardContainer;
    private professorDirectory profHistory;
    private courseDirectory courseHistory;
    private QueryHistory feedback;
    private studentDirectory studentHistory;
    private admin Admin;
    private thirdParty ThirdParty;
    
    public MainPortalJPanel(JPanel cardContainer, professorDirectory profHistory, courseDirectory courseHistory, QueryHistory feedback, studentDirectory studentHistory, admin Admin, thirdParty ThirdParty) {
        initComponents();
        this.cardContainer = cardContainer;
        this.profHistory = profHistory;
        this.courseHistory = courseHistory;
        this.feedback = feedback;
        this.studentHistory = studentHistory;
        this.Admin = Admin;
        this.ThirdParty = ThirdParty;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStudentLogin = new javax.swing.JButton();
        btnRegisterProfessor = new javax.swing.JButton();
        btnProfessorLogin = new javax.swing.JButton();
        btnRegisterStudent = new javax.swing.JButton();
        btnAdminLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnThirdParty = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStudentLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStudentLogin.setText("Student Login");
        btnStudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentLoginActionPerformed(evt);
            }
        });
        add(btnStudentLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 140, 190, 58));

        btnRegisterProfessor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterProfessor.setText("Register for Professor");
        btnRegisterProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterProfessorActionPerformed(evt);
            }
        });
        add(btnRegisterProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 298, -1, 58));

        btnProfessorLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProfessorLogin.setText("Professor Login");
        btnProfessorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorLoginActionPerformed(evt);
            }
        });
        add(btnProfessorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 190, 58));

        btnRegisterStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterStudent.setText("Register for Student");
        btnRegisterStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterStudentActionPerformed(evt);
            }
        });
        add(btnRegisterStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 298, 190, 58));

        btnAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdminLogin.setText("Admin");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });
        add(btnAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 456, 190, 58));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Don't have an account? Sign up as");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 248, 370, 30));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME TO TECH TUTOR PORTAL");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 677, 70));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Please select your role to login");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 370, 30));

        btnThirdParty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThirdParty.setText("Grad Verify");
        btnThirdParty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThirdPartyActionPerformed(evt);
            }
        });
        add(btnThirdParty, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 456, 190, 58));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Administrative Login-");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 406, 370, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PortalUI/MicrosoftTeams-image (3).png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1450, 1100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfessorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorLoginActionPerformed
        // TODO add your handling code here:
        
        ProfessorLoginJPanel professorLoginJPanel = new ProfessorLoginJPanel(cardContainer, profHistory, courseHistory);
        cardContainer.add("ProfessorLoginJPanel", professorLoginJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnProfessorLoginActionPerformed

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
        
        AdminLoginJPanel adminLoginJPanel = new AdminLoginJPanel(Admin, feedback);
        cardContainer.add("ProfessorLoginJPanel", adminLoginJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnRegisterProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterProfessorActionPerformed
        // TODO add your handling code here:
        
          
        ProfessorRegisterJPanel professorLoginJPanel = new ProfessorRegisterJPanel(cardContainer, profHistory);
        cardContainer.add("ProfessorRegisterJPanel", professorLoginJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);

    }//GEN-LAST:event_btnRegisterProfessorActionPerformed

    private void btnStudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentLoginActionPerformed
        // TODO add your handling code here:
        
        StudentLoginJPanel studentLoginJPanel = new StudentLoginJPanel(cardContainer, studentHistory, courseHistory, Admin, ThirdParty);
        cardContainer.add("StudentLoginJPanel", studentLoginJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnStudentLoginActionPerformed

    private void btnRegisterStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterStudentActionPerformed
        // TODO add your handling code here:
        
        StudentRegisterJPanel studentRegisterJPanel = new StudentRegisterJPanel(cardContainer, studentHistory);
        cardContainer.add("StudentRegisterJPanel", studentRegisterJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnRegisterStudentActionPerformed

    private void btnThirdPartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThirdPartyActionPerformed
        // TODO add your handling code here:
        
        ThirdPartyLoginJPanel thirdPartyJPanel = new ThirdPartyLoginJPanel(cardContainer, ThirdParty);
        cardContainer.add("ThirdPartyJPanel", thirdPartyJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
        
    }//GEN-LAST:event_btnThirdPartyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnProfessorLogin;
    private javax.swing.JButton btnRegisterProfessor;
    private javax.swing.JButton btnRegisterStudent;
    private javax.swing.JButton btnStudentLogin;
    private javax.swing.JButton btnThirdParty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
