/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import AboutUI.AboutJPanel;
import ContactUsUI.ContactUsJPanel;
import PortalUI.MainPortalJPanel;
import business.QueryHistory;
import business.admin;
import business.course;
import business.courseDirectory;
import business.professor;
import business.professorDirectory;
import business.student;
import business.studentDirectory;
import business.thirdParty;
import java.awt.CardLayout;

/**
 *
 * @author pranavkapse
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private professorDirectory profHistory;
    private courseDirectory courseHistory;
    private QueryHistory feedback;
    private studentDirectory studentHistory;
    admin Admin = new admin();
    thirdParty ThirdParty = new thirdParty();
    
    public MainJFrame() {
        initComponents();
        profHistory = new professorDirectory();
        courseHistory = new courseDirectory();
        feedback = new QueryHistory();
        studentHistory = new studentDirectory();
        
        //admin Admin = new admin();
        this.Admin.setUsername("Admin");
        this.Admin.setPassword("Password@123");
        
        this.ThirdParty.setUsername("GradVerify");
        this.ThirdParty.setPassword("Password@123");
        
        hardcodedData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        optionPanel = new javax.swing.JPanel();
        btnMainPortal = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnContact = new javax.swing.JButton();
        cardContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setRequestFocusEnabled(false);

        optionPanel.setBorder(new javax.swing.border.MatteBorder(null));

        btnMainPortal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMainPortal.setText("Go to Portal");
        btnMainPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainPortalActionPerformed(evt);
            }
        });

        btnAbout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAbout.setText("About Site");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnContact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnContact.setText("Contact Us");
        btnContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnContact, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMainPortal))
                .addContainerGap())
        );

        optionPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAbout, btnContact, btnMainPortal});

        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnMainPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnContact, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(793, Short.MAX_VALUE))
        );

        optionPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAbout, btnContact, btnMainPortal});

        jSplitPane1.setLeftComponent(optionPanel);

        cardContainer.setBorder(new javax.swing.border.MatteBorder(null));
        cardContainer.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/MicrosoftTeams-image (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardContainer.add(jPanel1, "card2");

        jSplitPane1.setRightComponent(cardContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainPortalActionPerformed
        // TODO add your handling code here:
        MainPortalJPanel mainPortalJPanel = new MainPortalJPanel(cardContainer, profHistory, courseHistory, feedback, studentHistory, Admin, ThirdParty);
        cardContainer.add("MainPortalJPanel", mainPortalJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnMainPortalActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        
        AboutJPanel aboutJPanel = new AboutJPanel(cardContainer);
        cardContainer.add("AboutJPanel", aboutJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
        
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactActionPerformed
        // TODO add your handling code here:
        
        ContactUsJPanel contactUsJPanel = new ContactUsJPanel(cardContainer, feedback);
        cardContainer.add("AboutJPanel", contactUsJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
        
    }//GEN-LAST:event_btnContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnContact;
    private javax.swing.JButton btnMainPortal;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel optionPanel;
    // End of variables declaration//GEN-END:variables



    private void hardcodedData() {
        
        student Student1 = studentHistory.addStudent();
        
        Student1.setName("Akshay Datir");
        Student1.setStudentID("101");
        Student1.setEmailID("akshaydatir@neu.edu");
        Student1.setUsername("akshay");
        Student1.setPassword("akshay123");
        
        student Student2 = studentHistory.addStudent();
        
        Student2.setName("Anuj Pawar");
        Student2.setStudentID("102");
        Student2.setEmailID("anujpawar@gmail.com");
        Student2.setUsername("anuj");
        Student2.setPassword("anuj123");

        
        professor Professor1 = profHistory.addProfessor();
        
        Professor1.setName("Karl Bugrara");
        Professor1.setProfessorID("1");
        Professor1.setEmailID("bugrara.k@neu.edu");
        Professor1.setUsername("karl");
        Professor1.setPassword("karl123");
        
        professor Professor2 = profHistory.addProfessor();
        
        Professor2.setName("Yusuf Ozbek");
        Professor2.setProfessorID("2");
        Professor2.setEmailID("ozbek.y@neu.edu");
        Professor2.setUsername("yusuf");
        Professor2.setPassword("yusuf123");

        
        course Course1 = courseHistory.addCourse();
        
        Course1.setCourseProfessorName("Karl Bugrara");
        Course1.setCourseProfessorID("1");
        Course1.setCoursename("Application Engineering and Development");
        Course1.setCourseID("5100");
        Course1.setCourseSemester("Spring 23");
        Course1.setCourseDescription("Takes students in a step-by-step manner through the process of combining UX techniques, business processes, and complex data models to assemble user-friendly applications.");
        Course1.setCourseLanguage("English");
        Course1.setCourseRegion("USA");
        Course1.setCourseScheduleDay("Wednesday");
        Course1.setCourseScheduleTime("3 to 6 pm");
        
        course Course2 = courseHistory.addCourse();
        
        Course2.setCourseProfessorName("Yusuf Ozbek");
        Course2.setCourseProfessorID("2");
        Course2.setCoursename("Data Management and Database Design");
        Course2.setCourseID("6210");
        Course2.setCourseSemester("Spring 23");
        Course2.setCourseDescription("Studies design of information systems from a data perspective for engineering and business applications; data modeling including entity-relationship (E-R) and object approaches.");
        Course2.setCourseLanguage("English");
        Course2.setCourseRegion("USA");
        Course2.setCourseScheduleDay("Monday");
        Course2.setCourseScheduleTime("6 to 9 pm");
        
        
        Professor1.addCourses(Course1);
        Professor2.addCourses(Course2);
        
        Course1.addPastStudentToCourse(Student1);
        Course1.addCourseRating(3.9);
        Course2.addPastStudentToCourse(Student2);
        Course2.addCourseRating(3.8);
        
        Student1.addcompletedCourses(Course1);
        Student1.addCompletedCoursesGrades(3.8);
        Student1.addcompletedCourses(Course2);
        Student1.addCompletedCoursesGrades(3.6);
        
    }
}
