/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package StudentUI;

import business.admin;
import business.courseDirectory;
import business.student;
import business.studentDirectory;
import business.thirdParty;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kaush
 */
public class StudentLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentLoginJPanel
     */
    
    JPanel cardContainer;
    private studentDirectory studentHistory;
    private courseDirectory courseHistory;
    private admin Admin;
    private thirdParty ThirdParty;
    
    public StudentLoginJPanel(JPanel cardContainer, studentDirectory studentHistory, courseDirectory courseHistory, admin Admin, thirdParty ThirdParty) {
        initComponents();
        this.cardContainer = cardContainer;
        this.studentHistory = studentHistory;
        this.courseHistory = courseHistory;
        this.Admin = Admin;
        this.ThirdParty = ThirdParty;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnSlogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSloginuser = new javax.swing.JTextField();
        txtSloginpass = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 264, 150, -1));

        btnSlogin.setBackground(new java.awt.Color(51, 153, 255));
        btnSlogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnSlogin.setText("Login");
        btnSlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSloginActionPerformed(evt);
            }
        });
        add(btnSlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 388, 150, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome Back Student");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 550, 60));

        jLabel1.setText("Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 150, -1));

        txtSloginuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSloginuserActionPerformed(evt);
            }
        });
        add(txtSloginuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 184, 150, 40));

        txtSloginpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSloginpassActionPerformed(evt);
            }
        });
        add(txtSloginpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 298, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSloginActionPerformed
        // TODO add your handling code here:

        String enteredusername = txtSloginuser.getText();
        String enteredPassword = txtSloginpass.getText();
        
        ArrayList<student> studentList = studentHistory.getStudentList();
        boolean flag = false;
        student userStudent = null;
        
        for (student Student : studentList){
            String username = Student.getUsername();
            if (username.equals(enteredusername)){
                String password = Student.getPassword();
                if (password.equals(enteredPassword)){
                    flag = true;
                    userStudent = Student;
                    break;
                }
            }
        }
        
        if (flag == false){
            JOptionPane.showMessageDialog(this, "Invalid username or password");
            return;
        }
        
         StudentHomeJPanel studentHomeJPanel = new StudentHomeJPanel(cardContainer, studentHistory, userStudent, courseHistory, Admin, ThirdParty);
         cardContainer.add("StudentHomeJPanel", studentHomeJPanel);
         CardLayout layout = (CardLayout) cardContainer.getLayout();
         layout.next(cardContainer);
        
    }//GEN-LAST:event_btnSloginActionPerformed

    private void txtSloginuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSloginuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSloginuserActionPerformed

    private void txtSloginpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSloginpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSloginpassActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtSloginpass;
    private javax.swing.JTextField txtSloginuser;
    // End of variables declaration//GEN-END:variables
}
