/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package StudentUI;

import business.admin;
import business.course;
import business.courseDirectory;
import business.student;
import business.studentDirectory;
import business.thirdParty;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class studentViewTranscriptPanel extends javax.swing.JPanel {

    /**
     * Creates new form studentViewTranscriptPanel
     */
    
    JPanel cardContainer;
    private studentDirectory studentHistory;
    private student userStudent;
    private courseDirectory courseHistory;
    private admin Admin;
    private thirdParty ThirdParty;

    studentViewTranscriptPanel(JPanel cardContainer, studentDirectory studentHistory, courseDirectory courseHistory, student userStudent, admin Admin, thirdParty ThirdParty) {
        initComponents();
        
        this.cardContainer = cardContainer;
        this.studentHistory = studentHistory;
        this.userStudent = userStudent;
        this.courseHistory = courseHistory;
        this.Admin = Admin;
        this.ThirdParty = ThirdParty;
        
        populateTableCompletedCourses();
        populateTextFields();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBacktr = new javax.swing.JButton();
        btnLogouttr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentCompletedCourses = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        txtStudentID = new javax.swing.JTextField();
        txtStudentCummulativeGrades = new javax.swing.JTextField();
        txtStudentStatus = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBacktr.setBackground(new java.awt.Color(102, 204, 255));
        btnBacktr.setText("Back");
        btnBacktr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktrActionPerformed(evt);
            }
        });
        add(btnBacktr, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 60, -1, -1));

        btnLogouttr.setBackground(new java.awt.Color(255, 204, 204));
        btnLogouttr.setText("Logout");
        btnLogouttr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogouttrActionPerformed(evt);
            }
        });
        add(btnLogouttr, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tech Tutor E-Learning Academy");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 796, 35));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 116, 63, -1));

        jLabel3.setText("Student ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 156, 76, -1));

        tblStudentCompletedCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Semester", "Grades"
            }
        ));
        jScrollPane1.setViewportView(tblStudentCompletedCourses);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 205, 660, 256));

        jLabel4.setText("Status:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 484, 51, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Cummulative grades:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 484, 131, -1));

        jLabel6.setText("/4");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 484, -1, -1));
        add(txtStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 113, 268, -1));
        add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 153, 267, -1));
        add(txtStudentCummulativeGrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 481, 66, -1));

        txtStudentStatus.setText("Pass");
        add(txtStudentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 481, 112, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Director");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 593, 87, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tech Tutor E-Learning");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 617, 159, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBacktrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktrActionPerformed
        // TODO add your handling code here:
        
        cardContainer.remove(this);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.previous(cardContainer);
        
    }//GEN-LAST:event_btnBacktrActionPerformed

    private void btnLogouttrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogouttrActionPerformed
        // TODO add your handling code here:
        
        StudentLoginJPanel logOutPanel= new StudentLoginJPanel(cardContainer, studentHistory, courseHistory, Admin, ThirdParty);
        cardContainer.removeAll();
        cardContainer.add(logOutPanel);
        
    }//GEN-LAST:event_btnLogouttrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBacktr;
    private javax.swing.JButton btnLogouttr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudentCompletedCourses;
    private javax.swing.JTextField txtStudentCummulativeGrades;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentStatus;
    // End of variables declaration//GEN-END:variables

    private void populateTableCompletedCourses() {
        
        
        DefaultTableModel model = (DefaultTableModel) tblStudentCompletedCourses.getModel();
        model.setRowCount(0);
        
        ArrayList<course> completedCoursesList = userStudent.getCompletedCourses();
        ArrayList<Double> completedCoursesGradesList = userStudent.getCompletedCoursesGrades();
        
        for (course Course : completedCoursesList){
            Object[] row = new Object[4];
            row[0] = Course.getCourseID();
            row[1] = Course.getCoursename();
            row[2] = Course.getCourseSemester();
            row[3] = userStudent.getCourseGrades(Course);
            
            model.addRow(row);
            
        }
    }

    private void populateTextFields() {
        
        txtStudentName.setText(userStudent.getName());
        txtStudentID.setText(userStudent.getStudentID());
        String grades = Double.toString(userStudent.getStudentOverallGrade(userStudent));
        txtStudentCummulativeGrades.setText(grades);
        txtStudentStatus.setText("Pass");
        
    }
}
