/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package StudentUI;

import business.admin;
import business.courseDirectory;
import business.student;
import business.studentDirectory;
import business.thirdParty;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kaush
 */
public class StudentHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentHomeJPanel
     */
    JPanel cardContainer;
    private studentDirectory studentHistory;
    private student userStudent;
    private courseDirectory courseHistory;
    private admin Admin;
    private thirdParty ThirdParty;
    
    public StudentHomeJPanel(JPanel cardContainer, studentDirectory studentHistory, student userStudent, courseDirectory courseHistory, admin Admin, thirdParty ThirdParty) {
        initComponents();
        this.cardContainer = cardContainer;
        this.studentHistory = studentHistory;
        this.userStudent = userStudent;
        this.courseHistory = courseHistory;
        this.Admin = Admin;
        this.ThirdParty = ThirdParty;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCourses = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRequestTranscript = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome back to learning");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 720, 60));

        btnCourses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCourses.setText("Courses");
        btnCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoursesActionPerformed(evt);
            }
        });
        add(btnCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 180, 179, 35));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update Profile");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 180, 179, 35));

        btnRequestTranscript.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRequestTranscript.setText("Request For Transcript");
        btnRequestTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestTranscriptActionPerformed(evt);
            }
        });
        add(btnRequestTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 180, -1, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoursesActionPerformed
        // TODO add your handling code here:
        
        studentCourseRegisterJPanel courseJPanel = new studentCourseRegisterJPanel(cardContainer, studentHistory, userStudent, courseHistory, Admin, ThirdParty);
        cardContainer.add("CourseJPanel", courseJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnCoursesActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        studentUpdateJPanel updateStudentJPanel = new studentUpdateJPanel(cardContainer, studentHistory, userStudent, courseHistory, Admin, ThirdParty);
        cardContainer.add("UpdateStudentJPanel", updateStudentJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRequestTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestTranscriptActionPerformed
        // TODO add your handling code here:
        
        studentTranscriptJPanel transcriptJPanel = new studentTranscriptJPanel(cardContainer, studentHistory, userStudent, courseHistory, Admin, ThirdParty);
        cardContainer.add("TranscriptJPanel", transcriptJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnRequestTranscriptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourses;
    private javax.swing.JButton btnRequestTranscript;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
