/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package StudentUI;

import business.student;
import business.studentDirectory;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kaush
 */
public class StudentRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentRegisterJPanel
     */
    
    JPanel cardContainer;
    private studentDirectory studentHistory;
    
    public StudentRegisterJPanel(JPanel cardContainer, studentDirectory studentHistory) {
        initComponents();
        this.cardContainer = cardContainer;
        this.studentHistory = studentHistory;
        
    }

    /**StudentRegisterJPanel(JPanel cardContainer) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSsignupemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSjoin = new javax.swing.JButton();
        txtSsignupID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSsignupname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSsignupuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSsignuppass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtSsignupemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 149, 194, -1));

        jLabel6.setText("Password : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 214, -1, -1));

        btnSjoin.setBackground(new java.awt.Color(51, 153, 255));
        btnSjoin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSjoin.setForeground(new java.awt.Color(255, 255, 255));
        btnSjoin.setText("Join");
        btnSjoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSjoinActionPerformed(evt);
            }
        });
        add(btnSjoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 372, 150, 41));
        add(txtSsignupID, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 310, 194, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 770, 47));

        jLabel2.setText("Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 127, 70, -1));
        add(txtSsignupname, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 149, 194, -1));

        jLabel3.setText("UserName :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 214, 70, -1));
        add(txtSsignupuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 236, 194, -1));

        jLabel4.setText("ID : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 288, 70, -1));

        jLabel5.setText("E-Mail :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 127, 150, -1));

        txtSsignuppass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsignuppassActionPerformed(evt);
            }
        });
        add(txtSsignuppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 236, 194, -1));

        jLabel7.setText("1. Minimum Password length should be 8.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 466, -1, -1));

        jLabel8.setText("2. Password must contain atleast 1 Lower case and 1 Upper case character.");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 488, 403, 18));

        jLabel9.setText("3. Password must contain atleast 1 digit and 1 special character.");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 512, 464, -1));

        jLabel10.setText("Password Guidelines:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 444, 155, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSjoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSjoinActionPerformed
        // TODO add your handling code here:
        
        String name = txtSsignupname.getText();
        if (name.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter student name");
            return;
        }
        
        String email = txtSsignupemail.getText();
        if (email.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter student email");
            return;
        }
        
        String username = txtSsignupuser.getText();
        if (username.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter username");
            return;
        }
        
        String password= txtSsignuppass.getText();
        if (password.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter password");
            return;
        }
        
        try{
            Integer.parseInt(txtSsignupID.getText());
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(this, "Please enter only numbers in ID");
            return;
        }
        String ID = txtSsignupID.getText();
        
        boolean isStudUsernameUnique = studentHistory.isStudUsernameUnique(username);
        if (isStudUsernameUnique == false){
            JOptionPane.showMessageDialog(null, "This username already exist");
            return;
        }
        
        boolean isStudentIDUnique = studentHistory.isStudIDUnique(ID);
        if (isStudentIDUnique == false){
            JOptionPane.showMessageDialog(null, "This ID already exist");
            return;
        }
        
        if(isPasswordValid(password) == false){
            JOptionPane.showMessageDialog(null, "Please set password as per guidelines");
            return;
        }
        
        student Student = studentHistory.addStudent();
        
        Student.setName(name);
        Student.setEmailID(email);
        Student.setStudentID(ID);
        Student.setUsername(username);
        Student.setPassword(password);
        
        JOptionPane.showMessageDialog(this, "Student created");
        
        txtSsignupID.setText("");
        txtSsignupemail.setText("");
        txtSsignupname.setText("");
        txtSsignuppass.setText("");
        txtSsignupuser.setText("");
        
        
    }//GEN-LAST:event_btnSjoinActionPerformed
      public boolean isPasswordValid(String password) {
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=])(?=\\S+$).{8,}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(password);
        return matcher.matches();
    }
    private void txtSsignuppassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsignuppassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsignuppassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSjoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtSsignupID;
    private javax.swing.JTextField txtSsignupemail;
    private javax.swing.JTextField txtSsignupname;
    private javax.swing.JTextField txtSsignuppass;
    private javax.swing.JTextField txtSsignupuser;
    // End of variables declaration//GEN-END:variables
}



