/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProfessorUI;

import business.course;
import business.courseDirectory;
import business.professor;
import business.professorDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pranavkapse
 */
public class CreateCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCoursesJPanel
     */
    JPanel cardContainer;
    private professorDirectory profHistory;
    private courseDirectory courseHistory;
    private professor userProf;
    
    public CreateCoursesJPanel(JPanel cardContainer, professorDirectory profHistory, courseDirectory courseHistory, professor userProf) {
        initComponents();
        this.cardContainer = cardContainer;
        this.profHistory = profHistory;
        this.courseHistory = courseHistory;
        this.userProf = userProf;
        
        String profName = userProf.getName();
        txtProfessorName.setText(profName);
        txtProfessorName.setEnabled(false);
        
        String profID = userProf.getProfessorID();
        txtProfessorID.setText(profID);
        txtProfessorID.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtCourseDay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCourseId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        txtCourseRegion = new javax.swing.JTextField();
        txtCourseTime = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnCreateCourse = new javax.swing.JButton();
        txtCourseLanguage = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtProfessorID = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCourseDescription = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtProfessorName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbSemester = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCourseDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseDayActionPerformed(evt);
            }
        });
        jPanel2.add(txtCourseDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 224, 35));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CREATE COURSE");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 747, 68));

        txtCourseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtCourseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 224, 35));

        jLabel11.setText("Course Day:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 224, 25));

        jLabel12.setText("Course ID:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 224, 25));

        jLabel13.setText("Course Name:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 25));

        jLabel14.setText("Course Time:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 207, 25));

        jLabel15.setText("Course Region:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 224, 25));

        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 224, 35));

        txtCourseRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseRegionActionPerformed(evt);
            }
        });
        jPanel2.add(txtCourseRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 224, 35));

        txtCourseTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseTimeActionPerformed(evt);
            }
        });
        jPanel2.add(txtCourseTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 224, 35));

        jLabel16.setText("Course Description:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 224, 25));

        btnCreateCourse.setBackground(new java.awt.Color(102, 153, 255));
        btnCreateCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCreateCourse.setText("Create");
        btnCreateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCourseActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreateCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 98, 42));

        txtCourseLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseLanguageActionPerformed(evt);
            }
        });
        jPanel2.add(txtCourseLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 224, 35));

        jLabel17.setText("Course Language:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 224, 25));

        jLabel18.setText("Professor Name:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 74, 224, 25));

        txtProfessorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtProfessorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 224, 35));

        btnBack1.setBackground(new java.awt.Color(153, 204, 255));
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 30));

        btnLogOut.setBackground(new java.awt.Color(255, 204, 204));
        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 90, 30));

        txtCourseDescription.setColumns(20);
        txtCourseDescription.setRows(5);
        jScrollPane1.setViewportView(txtCourseDescription);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 520, 90));

        jLabel1.setText("Professor ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 110, -1));

        txtProfessorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtProfessorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 224, 35));

        jLabel2.setText("Semester:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 100, -1));

        cbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Fall 23", "Spring 24", "Summer 24", "Fall 24" }));
        jPanel2.add(cbSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCourseDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseDayActionPerformed

    private void txtCourseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseIdActionPerformed

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void txtCourseRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseRegionActionPerformed

    private void txtCourseTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseTimeActionPerformed

    private void btnCreateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCourseActionPerformed
        // TODO add your handling code here:
        
        /*
        String profName = txtProfessorName.getText();
        if (profName.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter professor name");
            return;
        }
        */
        
        /*
        try{
            Integer.parseInt(txtProfessorID.getText());
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(this, "Please enter only numbers in ID");
            return;
        }
        */
        
        
        //Code to create ne course
        
        String courseName = txtCourseName.getText();
        if (courseName.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter course name");
            return;
        }
        
        try{
            Integer.parseInt(txtCourseId.getText());
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(this, "Please enter only numbers in ID");
            return;
        }
        String courseID = txtCourseId.getText();
        
        String courseRegion = txtCourseRegion.getText();
        if (courseRegion.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter course region");
            return;
        }
        
        String courseLanguage = txtCourseLanguage.getText();
        if (courseLanguage.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter course region");
            return;
        }
        
        String courseDay = txtCourseDay.getText();
        if (courseDay.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter course region");
            return;
        }
        
        String courseTime = txtCourseTime.getText();
        if (courseTime.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter course region");
            return;
        }
        
        Object searchBySelected = cbSemester.getSelectedItem();
        String semester = searchBySelected.toString();
        
        if (semester.equals(" ")){
            JOptionPane.showMessageDialog(this, "Please select semester");
            return;
        }
        
        String courseDescription = txtCourseDescription.getText();
        if (courseDescription.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter course region");
            return;
        }
        
        
        boolean isCourseIDUnique = courseHistory.isCourseIDUnique(courseID);
        if (isCourseIDUnique == false){
            JOptionPane.showMessageDialog(this, "This course ID already exist");
            return;
        }
        
        
        course Course = courseHistory.addCourse();
        
        Course.setCourseProfessorName(userProf.getName());
        Course.setCourseProfessorID(userProf.getProfessorID());
        Course.setCoursename(courseName);
        Course.setCourseID(courseID);
        Course.setCourseRegion(courseRegion);
        Course.setCourseLanguage(courseLanguage);
        Course.setCourseScheduleDay(courseDay);
        Course.setCourseScheduleTime(courseTime);
        Course.setCourseSemester(semester);
        Course.setCourseDescription(courseDescription);
        
        userProf.addCourses(Course);
        
        JOptionPane.showMessageDialog(this, "Course created");
        
        txtProfessorName.setText("");
        txtProfessorID.setText("");
        txtCourseName.setText("");
        txtCourseId.setText("");
        txtCourseRegion.setText("");
        txtCourseLanguage.setText("");
        txtCourseDay.setText("");
        txtCourseTime.setText("");
        txtCourseDescription.setText("");
      
           
    }//GEN-LAST:event_btnCreateCourseActionPerformed

    private void txtCourseLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseLanguageActionPerformed

    private void txtProfessorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorIDActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        cardContainer.remove(this);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.previous(cardContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        ProfessorLoginJPanel logOutPanel= new ProfessorLoginJPanel(cardContainer, profHistory, courseHistory);
        cardContainer.removeAll();
        cardContainer.add(logOutPanel);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtProfessorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCreateCourse;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JComboBox<String> cbSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCourseDay;
    private javax.swing.JTextArea txtCourseDescription;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtCourseLanguage;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseRegion;
    private javax.swing.JTextField txtCourseTime;
    private javax.swing.JTextField txtProfessorID;
    private javax.swing.JTextField txtProfessorName;
    // End of variables declaration//GEN-END:variables
}
