/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProfessorUI;

import business.courseDirectory;
import business.professor;
import business.professorDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author pranavkapse
 */
public class ProfessorLandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorLandingJPanel
     */
    JPanel cardContainer;
    private professorDirectory profHistory;
    private courseDirectory courseHistory;
    private professor userProf;
    
    public ProfessorLandingJPanel(JPanel cardContainer, professorDirectory profHistory, courseDirectory courseHistory, professor userProf) {
        initComponents();
        this.cardContainer = cardContainer;
        this.profHistory = profHistory;
        this.courseHistory = courseHistory;
        this.userProf = userProf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnViewCourses = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnCreateCourses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewCourses.setBackground(new java.awt.Color(102, 153, 255));
        btnViewCourses.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnViewCourses.setText("View Courses");
        btnViewCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCoursesActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 218, 178, 47));

        btnLogOut.setBackground(new java.awt.Color(255, 204, 204));
        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 107, 90, 30));

        btnCreateCourses.setBackground(new java.awt.Color(102, 153, 255));
        btnCreateCourses.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnCreateCourses.setText("Create Courses");
        btnCreateCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCoursesActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreateCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 218, 179, 47));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WELCOME BACK PROFESSOR");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 786, 59));

        btnProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        jPanel2.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 217, 179, 47));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCoursesActionPerformed
        // TODO add your handling code here:
        
        ViewProfessorCoursesJPanel viewProfessorCoursesJPanel = new ViewProfessorCoursesJPanel(cardContainer, profHistory, courseHistory, userProf);
        cardContainer.add("ProfessorLandingJPanel", viewProfessorCoursesJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnViewCoursesActionPerformed

    private void btnCreateCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCoursesActionPerformed
        // TODO add your handling code here:
        
        CreateCoursesJPanel createCoursesJPanel = new CreateCoursesJPanel(cardContainer, profHistory, courseHistory, userProf);
        cardContainer.add("ProfessorLandingJPanel", createCoursesJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnCreateCoursesActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        
        cardContainer.remove(this);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.previous(cardContainer);
        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        
        professorProfile ProfessorProfile = new professorProfile(cardContainer, profHistory, courseHistory, userProf);
        cardContainer.add("professorProfile", ProfessorProfile);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
        
    }//GEN-LAST:event_btnProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCourses;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnViewCourses;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
