/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProfessorUI;

import business.courseDirectory;
import business.professor;
import business.professorDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kaush
 */
public class ProfessorLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorLoginJPanel
     */
    JPanel cardContainer;
    private professorDirectory profHistory;
    private courseDirectory courseHistory;
    //ArrayList<professor> profList = profHistory.getProfessorList();
    public ProfessorLoginJPanel(JPanel cardContainer, professorDirectory profHistory, courseDirectory courseHistory) {
        initComponents();
        this.cardContainer = cardContainer;
        this.profHistory = profHistory;
        this.courseHistory = courseHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPlogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPloginpass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPloginuser = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlogin.setBackground(new java.awt.Color(51, 153, 255));
        btnPlogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnPlogin.setText("Login");
        btnPlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPloginActionPerformed(evt);
            }
        });
        jPanel2.add(btnPlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 375, 150, 35));

        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 256, 150, -1));
        jPanel2.add(txtPloginpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 285, 150, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Welcome Back Professor");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 753, 60));

        jLabel7.setText("Username");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 150, 150, -1));
        jPanel2.add(txtPloginuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 185, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPloginActionPerformed
        // TODO add your handling code here:
        
        String enteredusername = txtPloginuser.getText();
        String enteredpassword = txtPloginpass.getText();
        
        ArrayList<professor> profList = profHistory.getProfessorList();
        boolean flag = false;
        professor userProf = null;
        
        for (professor prof : profList){
            String username = prof.getUsername();
            if (username.equals(enteredusername)){
                String password = prof.getPassword();
                if (password.equals(enteredpassword)){
                    flag = true;
                    userProf = prof;
                    break;
                }
            }
        }
        
        if (flag == false){
            JOptionPane.showMessageDialog(this, "Invalid username or password");
            return;
        }
        
        ProfessorLandingJPanel professorLandingJPanel = new ProfessorLandingJPanel(cardContainer, profHistory, courseHistory, userProf);
        cardContainer.add("ProfessorLandingJPanel", professorLandingJPanel);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.next(cardContainer);
    }//GEN-LAST:event_btnPloginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlogin;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtPloginpass;
    private javax.swing.JTextField txtPloginuser;
    // End of variables declaration//GEN-END:variables
}
