/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProfessorUI;

import business.professor;
import business.professorDirectory;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kaush
 */
public class ProfessorRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorRegisterJPanel
     */
    
    JPanel cardContainer;
    private professorDirectory profHistory;
    
    public ProfessorRegisterJPanel(JPanel cardContainer, professorDirectory profHistory) {
        initComponents();
        this.cardContainer = cardContainer;
        this.profHistory = profHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPjoin = new javax.swing.JButton();
        txtPsignupname = new javax.swing.JTextField();
        txtPsignupid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPsignupuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPsignupemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPsignuppass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 60));

        jLabel2.setText("Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 150, 70, -1));

        btnPjoin.setBackground(new java.awt.Color(51, 153, 255));
        btnPjoin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPjoin.setForeground(new java.awt.Color(255, 255, 255));
        btnPjoin.setText("Join");
        btnPjoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPjoinActionPerformed(evt);
            }
        });
        add(btnPjoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 444, 150, -1));
        add(txtPsignupname, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 181, 150, 37));
        add(txtPsignupid, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 377, 150, 37));

        jLabel3.setText("UserName :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 248, 70, -1));
        add(txtPsignupuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 279, 150, 37));

        jLabel4.setText("Professor ID :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 346, -1, -1));

        jLabel5.setText("E-Mail :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 150, 150, -1));
        add(txtPsignupemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 181, 150, 37));

        jLabel6.setText("Password : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 248, 150, -1));
        add(txtPsignuppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 279, 150, 37));

        jLabel7.setText("1. Minimum Password length should be 8.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 538, -1, -1));

        jLabel8.setText("2. Password must contain atleast 1 Lower case and 1 Upper case character.");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 560, 400, 15));

        jLabel9.setText("3. Password must contain atleast 1 digit and 1 special character.");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 581, -1, -1));

        jLabel10.setText("Password Guidelines-");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 516, 123, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPjoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPjoinActionPerformed
        // TODO add your handling code here:
        //Create new professor
        String name = txtPsignupname.getText();
        if (name.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter professor name");
            return;
        }
        
        String email = txtPsignupemail.getText();
        if (email.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter professor email");
            return;
        }
        
        String username = txtPsignupuser.getText();
        if (username.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter username");
            return;
        }
        
        String password= txtPsignuppass.getText();
        if (password.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter password");
            return;
        }
        
        try{
            Integer.parseInt(txtPsignupid.getText());
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(this, "Please enter only numbers in ID");
            return;
        }
        String ID = txtPsignupid.getText();
        
        boolean isProfUsernameUnique = profHistory.isProfUsernameUnique(username);
        if (isProfUsernameUnique == false){
            JOptionPane.showMessageDialog(null, "This username already exist");
            return;
        }
        
        boolean isProfIDUnique = profHistory.isProfIDUnique(ID);
        if (isProfIDUnique == false){
            JOptionPane.showMessageDialog(null, "This ID already exist");
            return;
        }
        
         if(isPasswordValid(password) == false){
            JOptionPane.showMessageDialog(null, "Please set password as per guidelines");
            return;
        }
        
        professor Professor = profHistory.addProfessor();
        
        Professor.setName(name);
        Professor.setEmailID(email);
        Professor.setProfessorID(ID);
        Professor.setUsername(username);
        Professor.setPassword(password);
        
        JOptionPane.showMessageDialog(this, "Professor created");
        
        txtPsignupname.setText("");
        txtPsignupemail.setText("");
        txtPsignupid.setText("");
        txtPsignuppass.setText("");
        txtPsignupuser.setText("");
        
    }//GEN-LAST:event_btnPjoinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPjoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtPsignupemail;
    private javax.swing.JTextField txtPsignupid;
    private javax.swing.JTextField txtPsignupname;
    private javax.swing.JTextField txtPsignuppass;
    private javax.swing.JTextField txtPsignupuser;
    // End of variables declaration//GEN-END:variables

    private boolean isPasswordValid(String password) {
       String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=])(?=\\S+$).{8,}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(password);
        return matcher.matches();
    }
}