/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProfessorUI;

import business.course;
import business.courseDirectory;
import business.professorDirectory;
import business.student;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pranavkapse
 */
public class ViewProfessorDetails3JPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewProfessorDetails3JPanel
     */
    JPanel cardContainer;
    private professorDirectory profHistory;
    private courseDirectory courseHistory;
    private course selectedCourse;
    private student selectedStudent;
    
    public ViewProfessorDetails3JPanel(JPanel cardContainer, professorDirectory profHistory, courseDirectory courseHistory, course selectedCourse) {
        initComponents();
        this.cardContainer = cardContainer;
        this.profHistory = profHistory;
        this.courseHistory = courseHistory;
        this.selectedCourse = selectedCourse;
        
        populateStudentDetailsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentDetailsPane = new javax.swing.JScrollPane();
        tblStudentDetails = new javax.swing.JTable();
        btnGrades = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        txtGrades = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblStudentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Semester"
            }
        ));
        studentDetailsPane.setViewportView(tblStudentDetails);

        jPanel1.add(studentDetailsPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 154, 708, 283));

        btnGrades.setBackground(new java.awt.Color(102, 153, 255));
        btnGrades.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnGrades.setText("Grades Student");
        btnGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradesActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 455, -1, 36));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENTS REGISTERED FOR COURSE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 798, -1));

        btnBack.setBackground(new java.awt.Color(102, 204, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 79, 90, 30));

        btnLogOut.setBackground(new java.awt.Color(255, 204, 204));
        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 79, 90, 30));

        txtGrades.setEnabled(false);
        jPanel1.add(txtGrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 524, 50, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Grades:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 524, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("/ 4");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 524, 30, -1));

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 521, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradesActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblStudentDetails.getSelectedRow();
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select the course");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblStudentDetails.getModel();
        String studentID = (String) model.getValueAt(selectedRowIndex, 0);
        
        ArrayList<student> studentList = selectedCourse.getRegisteredOngoingStudents();
        
        for (student Student : studentList){
            if (Student.getStudentID().equals(studentID)){
                this.selectedStudent = Student;
                break;
            }
        }
        
        txtGrades.setEnabled(true);
        btnSave.setEnabled(true);
        
        
    }//GEN-LAST:event_btnGradesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        cardContainer.remove(this);
        CardLayout layout = (CardLayout) cardContainer.getLayout();
        layout.previous(cardContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        
        ProfessorLoginJPanel logOutPanel= new ProfessorLoginJPanel(cardContainer, profHistory, courseHistory);
        cardContainer.removeAll();
        cardContainer.add(logOutPanel);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        Double grades = Double.parseDouble(txtGrades.getText());
        if (grades < 0 || grades > 4){
            JOptionPane.showMessageDialog(this, "Please enter valid grades");
            return;
        }
        this.selectedStudent.addcompletedCourses(selectedCourse);
        selectedCourse.addPastStudentToCourse(selectedStudent);
        this.selectedStudent.addCompletedCoursesGrades(grades);
        JOptionPane.showMessageDialog(this, "Student graded");
        txtGrades.setEnabled(false);
        btnSave.setEnabled(false);
        
        populateStudentDetailsTable();
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGrades;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane studentDetailsPane;
    private javax.swing.JTable tblStudentDetails;
    private javax.swing.JTextField txtGrades;
    // End of variables declaration//GEN-END:variables

    private void populateStudentDetailsTable() {
        DefaultTableModel model = (DefaultTableModel) tblStudentDetails.getModel();
        model.setRowCount(0);
        
        ArrayList<student> studentList = selectedCourse.getRegisteredOngoingStudents();
        
        for (student Student : studentList){
            Object[] row = new Object[3];
            row[0] = Student.getStudentID();
            row[1] = Student.getName();
            row[2] = selectedCourse.getCourseSemester();
            
            model.addRow(row);
            
        }
    }
}
