/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminUI;

import business.QueryHistory;
import business.admin;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author pranavkapse
 */
public class AdminLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminLoginJPanel
     */
    
    private admin Admin;
    QueryHistory feedback;

    public AdminLoginJPanel(admin Admin, QueryHistory feedback){
        initComponents();
        this.Admin = Admin;
        this.feedback = feedback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtPassword = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblAdminLoginPage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        cardContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardContainer.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 197, 40));

        lblUsername.setText("Username");
        jPanel3.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 141, -1, -1));
        jPanel3.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 197, 40));

        lblPassword.setText("Password");
        jPanel3.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 238, -1, -1));

        btnLogin.setBackground(new java.awt.Color(102, 102, 255));
        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 106, 36));

        lblAdminLoginPage.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblAdminLoginPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminLoginPage.setText("Welcome Back Admin");
        jPanel3.add(lblAdminLoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 598, 61));

        cardContainer.add(jPanel3, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        
        //Validating the username and password
        if(Admin.getUsername().equals(username) && Admin.getPassword().equals(password)){
            JOptionPane.showMessageDialog(this, "Login Successful");
            ViewAdminJPanel viewAdminJPanel = new ViewAdminJPanel(feedback, Admin);
            cardContainer.add("ViewAdminJPanel", viewAdminJPanel);
            CardLayout layout = (CardLayout) cardContainer.getLayout();
            layout.next(cardContainer);
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid username or password");
            txtUsername.setText("");
            txtPassword.setText("");
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAdminLoginPage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
