/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminUI;

import business.Queries;
import business.QueryHistory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pranavkapse
 */
public class ViewUserFeedbackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewUserFeedbackJPanel
     */
    QueryHistory feedback;
    
    public ViewUserFeedbackJPanel(QueryHistory feedback) {
        initComponents();
        this.feedback = feedback;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblfeedback = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblfeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Email ID", "Feedback"
            }
        ));
        jScrollPane1.setViewportView(tblfeedback);
        if (tblfeedback.getColumnModel().getColumnCount() > 0) {
            tblfeedback.getColumnModel().getColumn(0).setMinWidth(100);
            tblfeedback.getColumnModel().getColumn(1).setMinWidth(100);
            tblfeedback.getColumnModel().getColumn(2).setMinWidth(350);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 790, 330));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblfeedback;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblfeedback.getModel();
        model.setRowCount(0);
        
        for(Queries q : feedback.getHistory()){
            
            Object[] row = new Object[10];
            //row[0] = pi;
            row[0] = q.getName();
            row[1] = q.getEmailId();
            row[2] = q.getQueries();

            model.addRow(row);
        } 
         
   }
}
