/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminUI;

import business.QueryHistory;
import business.admin;

/**
 *
 * @author pranavkapse
 */

public class ViewAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAdminJPanel
     */
    private QueryHistory feedback;
    private admin Admin;
    
    public ViewAdminJPanel(QueryHistory feedback, admin Admin) {
        initComponents();
        this.feedback = feedback;
        this.Admin = Admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblRequests = new javax.swing.JLabel();
        btnViewRequests = new javax.swing.JButton();
        lblRequests1 = new javax.swing.JLabel();
        btnViewFeedback = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(240);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setLastDividerLocation(120);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome back Admin");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 31, 752, 59));

        lblRequests.setText("See User Feedback/Queries");
        jPanel3.add(lblRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 159, 50));

        btnViewRequests.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewRequests.setText("View");
        btnViewRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestsActionPerformed(evt);
            }
        });
        jPanel3.add(btnViewRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 130, 128, 50));

        lblRequests1.setText("Pending requests for transcript");
        jPanel3.add(lblRequests1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 130, -1, 50));

        btnViewFeedback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewFeedback.setText("View feedback");
        btnViewFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFeedbackActionPerformed(evt);
            }
        });
        jPanel3.add(btnViewFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 130, 128, 50));

        jSplitPane1.setTopComponent(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jSplitPane1.setRightComponent(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestsActionPerformed
        // TODO add your handling code here:
        ViewStudentRequestJPanel viewStudentRequestJPanel = new ViewStudentRequestJPanel(Admin);
        jSplitPane1.setBottomComponent(viewStudentRequestJPanel);
    }//GEN-LAST:event_btnViewRequestsActionPerformed

    private void btnViewFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFeedbackActionPerformed
        // TODO add your handling code here:
        ViewUserFeedbackJPanel viewUserFeedbackJPanel = new ViewUserFeedbackJPanel(feedback);
        jSplitPane1.setBottomComponent(viewUserFeedbackJPanel);        
    }//GEN-LAST:event_btnViewFeedbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewFeedback;
    private javax.swing.JButton btnViewRequests;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblRequests;
    private javax.swing.JLabel lblRequests1;
    // End of variables declaration//GEN-END:variables
}
