/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ContactUsUI;

import business.Queries;
import business.QueryHistory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pranavkapse
 */
public class ContactUsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContactUsJPanel
     */
    
    JPanel cardContainer;
    QueryHistory feedback;
    
    public ContactUsJPanel(JPanel cardContainer, QueryHistory feedback) {
        initComponents();
        this.cardContainer = cardContainer;
        this.feedback = feedback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmailID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestions = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contact Us");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 786, 47));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Other Issue:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 129, -1, 42));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Admission Realted Issue:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 81, -1, 42));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel4.setText("admissionTechTutor@gmail.com");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 210, -1));

        jLabel5.setText("generalTechTutor@gmail.com");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 210, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Any suggestion or queries");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 220, 786, -1));

        jLabel7.setText("Name:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 273, 69, 31));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 598, 90, 40));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 234, 44));

        jLabel8.setText("Email ID:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 366, 69, 31));

        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });
        add(txtEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 403, 234, 43));

        jLabel9.setText("Queries or Suggestions:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 452, -1, 31));

        txtQuestions.setColumns(20);
        txtQuestions.setRows(5);
        jScrollPane1.setViewportView(txtQuestions);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 489, 397, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ContactUsUI/MicrosoftTeams-image (1).png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -4, 1360, 1100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
           
        String name = txtName.getText();
        if (name.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter name");
            return;
        }
        
        String email = txtEmailID.getText();
        if (email.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter email");
            return;
        }
        
        String question = txtQuestions.getText();
        if (question.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter your question");
            return;
        }
        
        Queries q = feedback.addNewVitals();
        
        q.setName(name);
        q.setEmailId(email);
        q.setQueries(question);
      
        
        JOptionPane.showMessageDialog(this, "Your Queries/Suggestions submitted successfully.");
        
        txtName.setText("");
        txtEmailID.setText("");
        txtQuestions.setText("");
        
        JOptionPane.showMessageDialog(this, "You will get response shortly, Thank you!");

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtQuestions;
    // End of variables declaration//GEN-END:variables
}
